server:
  port: 8082

spring:
  application:
    name: index-service

eureka:
  client:
    service-url:
#      defaultZone: http://127.0.0.1:9090/eureka,http://127.0.0.1:9091/eureka
      defaultZone: http://127.0.0.1:9090/eureka

feign:
  hystrix:
    enabled: true
