server:
  port: 8888

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      #      defaultZone: http://127.0.0.1:9090/eureka,http://127.0.0.1:9091/eureka
      defaultZone: http://127.0.0.1:9090/eureka
zuul:
  routes:
    index-service:
      path: /index/**
      serviceId: index-service
    product-service:
      path: /product/**
      serviceId: product-service
