server:
  port: 9090

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:9091/eureka
#
#spring:
#  application:
#    name: eureka-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false